name: secret_notes_v2
description: Secret Notes

publish_to: 'none'

version: 2.0.0+4

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  google_mobile_ads: ^2.3.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.2.1
  flutter_launcher_icons: ^0.11.0
  splash_screen_view: ^3.0.0
  change_app_package_name: ^1.1.0
  vocsy_esys_flutter_share: ^1.0.2

  


dev_dependencies:
splash_screen_view:
  background_image: images/1.png
  android: true
  ios: false
  web: false
  android_gravity: fill
  fullscreen: true


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "images/1.png"
  min_sdk_android: 21

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/